---
repos:
  - repo: builtin
    hooks:
      - id: check-case-conflict
        name: "🔠 Checking for case conflicts"
      - id: check-executables-have-shebangs
        name: "🧐 Checking that executables have shebangs"
        types: [text, executable]
        stages: [pre-commit, pre-push, manual]
      - id: check-json
        name: "｛ Checking JSON files"
        types: [json]
      - id: check-merge-conflict
        name: "💥 Checking for merge conflicts"
        types: [text]
      - id: check-symlinks
        name: "🔗 Checking for broken symlinks"
        types: [symlink]
      - id: check-toml
        name: "✅ Checking TOML files"
        types: [toml]
      - id: detect-private-key
        name: "🕵️  Detecting private keys"
        types: [text]
      - id: end-of-file-fixer
        name: "🔚 Checking end of files"
        types: [text]
        stages: [pre-commit, pre-push, manual]
      - id: fix-byte-order-marker
        name: "🚏 Checking UTF-8 byte order marker"
        types: [text]
      - id: no-commit-to-branch
        name: "🛑 Checking for commit to protected branch"
        pass_filenames: false
        always_run: true
        args:
          - --branch=development
          - --branch=main
      - id: trailing-whitespace
        name: "✄  Trimming trailing whitespace"
        types: [text]
        stages: [pre-commit, pre-push, manual]

  - repo: local
    hooks:
      - id: blacken-docs
        name: "☕️ Format documentation using black"
        language: system
        files: '\.(rst|md|markdown|py|tex)$'
        entry: uv run blacken-docs
        require_serial: true
      - id: check-ast
        name: "🐍 Checking Python AST"
        language: system
        types: [python]
        entry: uv run check-ast
      - id: check-docstring-first
        name: "ℹ️  Checking docstrings are first"
        language: system
        types: [python]
        entry: uv run check-docstring-first
      - id: codespell
        name: "✅ Checking code for misspellings"
        language: system
        types: [text]
        exclude: |
          (?x)^($^
          |.*uv\.lock
          )$
        entry: uv run codespell
      - id: debug-statements
        name: "🪵 Checking for debug statements and imports (Python)"
        language: system
        types: [python]
        entry: uv run debug-statement-hook
      - id: format
        name: "☕️ Formatting code using ruff"
        language: system
        types: [python]
        entry: uv run ruff format
      - id: mypy
        name: "🆎 Performing static type checking using mypy"
        language: system
        types: [python]
        entry: uv run mypy
      - id: ruff
        name: "👔 Enforcing style guide with ruff"
        language: system
        types: [python]
        entry: uv run ruff check --fix
        require_serial: true
      - id: uv-lock
        name: "🔒 Ensure the uv.lock file is up to date"
        language: system
        entry: uv lock --locked
        files: pyproject.toml$
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        name: "💄 Ensuring files are prettier"
