name: Create Release PR

"on":
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The CalVer version number
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pull-request:
    name: 🚀 Create Release PR

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🏗 Set up Python
        id: setup-python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.14.7

      - name: 🚜 Install uv
        uses: ./.github/actions/install-uv

      - name: 🏗 Install workflow dependencies
        run: |
          uv sync --extra release

      - name: 🔢 Update pyproject.toml version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          uv run ./scripts/bump-version.py "$VERSION"
          git checkout -b release/$VERSION
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pyproject.toml
          git commit -m "Update version to $VERSION"
          git tag \
            -a $VERSION \
            -m "Release $VERSION"
          git push origin release/$VERSION
          git push origin tag $VERSION

      - name: 📝 Create the PR
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --head release/$VERSION \
            --base main \
            --title "chore(release): $VERSION" \
            --body-file ".github/PULL_REQUEST_TEMPLATE/release.md" \
            --draft \
            --label release

      - name: ✏️ Run Release Drafter
        uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        with:
          tag: ${{ inputs.version }}
          name: ${{ inputs.version }}
          version: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
