---
name: Create Release

"on":
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create_release:
    name: 🚀 Create Release

    runs-on: ubuntu-latest

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 🏗 Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13.7

      - name: 🚜 Install uv
        uses: ./.github/actions/install-uv

      - name: 🚀 Publish to PyPi
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_API_KEY }}
