name: Lint Pull Request

"on":
  pull_request_target:
    branches:
      - development
      - main
      - release/*
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write

jobs:
  lint-title:
    name: 🧹 Lint Pull Request

    runs-on: ubuntu-latest

    steps:
      - name: Lint title
        uses: amannn/action-semantic-pull-request@v5
        id: lint-title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create error comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ always() && steps.lint-title.outputs.error_message != null }}
        with:
          header: lint-title-error-comment
          message: |
            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like this pull request's title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint-title.outputs.error_message }}
            ```

      - name: Delete error comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.lint-title.outputs.error_message == null }}
        with:
          header: lint-title-error-comment
          delete: true
