name: Sync Labels

on:
  push:
    branches:
      - development
    paths:
      - .github/config/labels.yml
      - .github/workflows/sync-labels.yml

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Labels
        uses: liminal-ai-security/actions-hub/.github/actions/sync-labels@v5
        with:
          label_path: "./.github/config/labels.yml"
